apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-app
  labels:
    app: springboot-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: springboot-app
  template:
    metadata:
      labels:
        app: springboot-app
    spec:
      containers:
      - name: springboot-app
        image: crpi-t5ahmm8it9ift170.cn-hangzhou.personal.cr.aliyuncs.com/timmyhu/fraud_detection:0.0.2
        imagePullPolicy: Always  # 强制每次拉取最新镜像
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "100m"
            memory: "100Mi"
          limits:
            cpu: "200m"
            memory: "200Mi"